-- ============================================================
-- 002: Phase 3 Academic Seed — RETIRED (DO NOT RUN)
-- ============================================================
-- This file originally contained invalid SQL (malformed INSERT syntax) and
-- targeted snake_case columns that never existed in the live database.
-- It was never applied anywhere and cannot be applied.
--
-- The corrected, working seed lives in:
--   005-phase3-academic-seed.sql
--
-- Everything below is a harmless no-op.
SELECT 1;
