-- 006: convert varchar FK/reference columns to uuid across the live schema.
-- RLS policies reference tenantId columns, so this transaction:
--   1. drops all policies on public tables (captured below verbatim)
--   2. runs the ALTER COLUMN ... TYPE uuid statements (same 315 columns as the entity codemod)
--   3. re-creates the policies exactly as captured
-- Excluded (intentionally left varchar — not uuid references):
--   audit_events.correlationId/requestId/entityId, workflow_instances.entityId,
--   rebac_edges.objectId/subjectUserId, refunds.originalOrId (receipt no.),
--   notification_logs.providerMsgId (external), messages.threadId (grouping key),
--   channel_configs.senderId (external)
BEGIN;

-- ===== policy drops (101) =====
DROP POLICY IF EXISTS "tenant_isolation_users" ON "users";
DROP POLICY IF EXISTS "tenant_isolation_roles" ON "roles";
DROP POLICY IF EXISTS "tenant_isolation_user_roles" ON "user_roles";
DROP POLICY IF EXISTS "tenant_isolation_lookup_lists" ON "lookup_lists";
DROP POLICY IF EXISTS "tenant_isolation_custom_field_definitions" ON "custom_field_definitions";
DROP POLICY IF EXISTS "tenant_isolation_feature_flags" ON "feature_flags";
DROP POLICY IF EXISTS "tenant_isolation_enrollment_holds" ON "enrollment_holds";
DROP POLICY IF EXISTS "tenant_isolation_applicant_stage_configs" ON "applicant_stage_configs";
DROP POLICY IF EXISTS "tenant_isolation_attendance_excuses" ON "attendance_excuses";
DROP POLICY IF EXISTS "tenant_isolation_attendance_config" ON "attendance_config";
DROP POLICY IF EXISTS "tenant_isolation_channel_configs" ON "channel_configs";
DROP POLICY IF EXISTS "tenant_isolation_announcements" ON "announcements";
DROP POLICY IF EXISTS "tenant_isolation_atp_series" ON "atp_series";
DROP POLICY IF EXISTS "tenant_isolation_cashier_sessions" ON "cashier_sessions";
DROP POLICY IF EXISTS "tenant_isolation_ad_hoc_sale_items" ON "ad_hoc_sale_items";
DROP POLICY IF EXISTS "tenant_isolation_ad_hoc_sales" ON "ad_hoc_sales";
DROP POLICY IF EXISTS "tenant_isolation_tenants" ON "tenants";
DROP POLICY IF EXISTS "tenant_isolation_discount_types" ON "discount_types";
DROP POLICY IF EXISTS "tenant_isolation_education_levels" ON "education_levels";
DROP POLICY IF EXISTS "tenant_isolation_branches" ON "branches";
DROP POLICY IF EXISTS "tenant_isolation_buildings" ON "buildings";
DROP POLICY IF EXISTS "tenant_isolation_departments" ON "departments";
DROP POLICY IF EXISTS "tenant_isolation_fee_structure_items" ON "fee_structure_items";
DROP POLICY IF EXISTS "tenant_isolation_applicant_stage_transitions" ON "applicant_stage_transitions";
DROP POLICY IF EXISTS "tenant_isolation_attendance_notification_thresholds" ON "attendance_notification_thresholds";
DROP POLICY IF EXISTS "tenant_isolation_attendance_records" ON "attendance_records";
DROP POLICY IF EXISTS "tenant_isolation_audit_events" ON "audit_events";
DROP POLICY IF EXISTS "tenant_isolation_behavior_incidents" ON "behavior_incidents";
DROP POLICY IF EXISTS "tenant_isolation_calendar_events" ON "calendar_events";
DROP POLICY IF EXISTS "tenant_isolation_cashier_stations" ON "cashier_stations";
DROP POLICY IF EXISTS "tenant_isolation_class_offerings" ON "class_offerings";
DROP POLICY IF EXISTS "tenant_isolation_curricula" ON "curricula";
DROP POLICY IF EXISTS "tenant_isolation_curriculum_subjects" ON "curriculum_subjects";
DROP POLICY IF EXISTS "tenant_isolation_denomination_sets" ON "denomination_sets";
DROP POLICY IF EXISTS "tenant_isolation_document_requests" ON "document_requests";
DROP POLICY IF EXISTS "tenant_isolation_document_templates" ON "document_templates";
DROP POLICY IF EXISTS "tenant_isolation_dtr_records" ON "dtr_records";
DROP POLICY IF EXISTS "tenant_isolation_employees" ON "employees";
DROP POLICY IF EXISTS "tenant_isolation_enrollments" ON "enrollments";
DROP POLICY IF EXISTS "tenant_isolation_faculty_load_limits" ON "faculty_load_limits";
DROP POLICY IF EXISTS "tenant_isolation_fee_structures" ON "fee_structures";
DROP POLICY IF EXISTS "tenant_isolation_fee_types" ON "fee_types";
DROP POLICY IF EXISTS "tenant_isolation_floors" ON "floors";
DROP POLICY IF EXISTS "tenant_isolation_generated_documents" ON "generated_documents";
DROP POLICY IF EXISTS "tenant_isolation_grade_change_requests" ON "grade_change_requests";
DROP POLICY IF EXISTS "tenant_isolation_grade_components" ON "grade_components";
DROP POLICY IF EXISTS "tenant_isolation_grade_entries" ON "grade_entries";
DROP POLICY IF EXISTS "tenant_isolation_grade_levels" ON "grade_levels";
DROP POLICY IF EXISTS "tenant_isolation_grading_systems" ON "grading_systems";
DROP POLICY IF EXISTS "tenant_isolation_guardians" ON "guardians";
DROP POLICY IF EXISTS "tenant_isolation_health_records" ON "health_records";
DROP POLICY IF EXISTS "tenant_isolation_honor_roll_configs" ON "honor_roll_configs";
DROP POLICY IF EXISTS "tenant_isolation_installment_schedules" ON "installment_schedules";
DROP POLICY IF EXISTS "tenant_isolation_invoice_items" ON "invoice_items";
DROP POLICY IF EXISTS "tenant_isolation_invoices" ON "invoices";
DROP POLICY IF EXISTS "tenant_isolation_lookup_items" ON "lookup_items";
DROP POLICY IF EXISTS "tenant_isolation_message_threads" ON "message_threads";
DROP POLICY IF EXISTS "tenant_isolation_messages" ON "messages";
DROP POLICY IF EXISTS "tenant_isolation_notification_logs" ON "notification_logs";
DROP POLICY IF EXISTS "tenant_isolation_notification_rules" ON "notification_rules";
DROP POLICY IF EXISTS "tenant_isolation_notification_templates" ON "notification_templates";
DROP POLICY IF EXISTS "tenant_isolation_numbering_schemes" ON "numbering_schemes";
DROP POLICY IF EXISTS "tenant_isolation_official_receipts" ON "official_receipts";
DROP POLICY IF EXISTS "tenant_isolation_payment_allocations" ON "payment_allocations";
DROP POLICY IF EXISTS "tenant_isolation_payment_methods" ON "payment_methods";
DROP POLICY IF EXISTS "tenant_isolation_payment_plans" ON "payment_plans";
DROP POLICY IF EXISTS "tenant_isolation_payments" ON "payments";
DROP POLICY IF EXISTS "tenant_isolation_penalty_rules" ON "penalty_rules";
DROP POLICY IF EXISTS "tenant_isolation_permanent_records" ON "permanent_records";
DROP POLICY IF EXISTS "tenant_isolation_programs" ON "programs";
DROP POLICY IF EXISTS "tenant_isolation_rebac_edges" ON "rebac_edges";
DROP POLICY IF EXISTS "tenant_isolation_promotion_decisions" ON "promotion_decisions";
DROP POLICY IF EXISTS "tenant_isolation_refunds" ON "refunds";
DROP POLICY IF EXISTS "tenant_isolation_report_templates" ON "report_templates";
DROP POLICY IF EXISTS "tenant_isolation_room_assets" ON "room_assets";
DROP POLICY IF EXISTS "tenant_isolation_rooms" ON "rooms";
DROP POLICY IF EXISTS "tenant_isolation_scheduled_reports" ON "scheduled_reports";
DROP POLICY IF EXISTS "tenant_isolation_school_calendars" ON "school_calendars";
DROP POLICY IF EXISTS "tenant_isolation_school_years" ON "school_years";
DROP POLICY IF EXISTS "tenant_isolation_section_assignment_rules" ON "section_assignment_rules";
DROP POLICY IF EXISTS "tenant_isolation_sections" ON "sections";
DROP POLICY IF EXISTS "tenant_isolation_series_counters" ON "series_counters";
DROP POLICY IF EXISTS "tenant_isolation_strands" ON "strands";
DROP POLICY IF EXISTS "tenant_isolation_student_discount_grants" ON "student_discount_grants";
DROP POLICY IF EXISTS "tenant_isolation_student_documents" ON "student_documents";
DROP POLICY IF EXISTS "tenant_isolation_student_guardians" ON "student_guardians";
DROP POLICY IF EXISTS "tenant_isolation_student_merge_audit" ON "student_merge_audit";
DROP POLICY IF EXISTS "tenant_isolation_student_schedules" ON "student_schedules";
DROP POLICY IF EXISTS "tenant_isolation_student_section_assignments" ON "student_section_assignments";
DROP POLICY IF EXISTS "tenant_isolation_student_transfers" ON "student_transfers";
DROP POLICY IF EXISTS "tenant_isolation_students" ON "students";
DROP POLICY IF EXISTS "tenant_isolation_subjects" ON "subjects";
DROP POLICY IF EXISTS "tenant_isolation_teaching_loads" ON "teaching_loads";
DROP POLICY IF EXISTS "tenant_isolation_terms" ON "terms";
DROP POLICY IF EXISTS "tenant_isolation_tracks" ON "tracks";
DROP POLICY IF EXISTS "tenant_isolation_user_person_links" ON "user_person_links";
DROP POLICY IF EXISTS "tenant_isolation_user_sessions" ON "user_sessions";
DROP POLICY IF EXISTS "tenant_isolation_withdrawal_policies" ON "withdrawal_policies";
DROP POLICY IF EXISTS "tenant_isolation_workflow_approvals" ON "workflow_approvals";
DROP POLICY IF EXISTS "tenant_isolation_workflow_definitions" ON "workflow_definitions";
DROP POLICY IF EXISTS "tenant_isolation_workflow_instances" ON "workflow_instances";

-- ===== column type conversions (315) =====
-- 000-create-all-tables.sql now derives every column type from the entity
-- metadata, so a database built from the current migration set is ALREADY uuid
-- and these conversions would fail ("function pg_catalog.btrim(uuid) does not
-- exist"). They still matter for a database that predates this file, and ALTER
-- cannot be wrapped in a conditional, so gate the whole section on whether two
-- representative columns are still text. No-ops on an up-to-date schema.
SELECT (
         COALESCE(
           (SELECT data_type FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'ad_hoc_sale_items'
               AND column_name = 'adHocSaleId') <> 'uuid',
           false)
         OR COALESCE(
           (SELECT data_type FROM information_schema.columns
             WHERE table_schema = 'public' AND table_name = 'user_person_links'
               AND column_name = 'tenantId') <> 'uuid',
           false)
       ) AS legacy_text_columns \gset
\if :legacy_text_columns
ALTER TABLE "ad_hoc_sale_items" ALTER COLUMN "adHocSaleId" TYPE uuid USING NULLIF(trim("adHocSaleId"), '')::uuid;
ALTER TABLE "ad_hoc_sale_items" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "ad_hoc_sales" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "ad_hoc_sales" ALTER COLUMN "sessionId" TYPE uuid USING NULLIF(trim("sessionId"), '')::uuid;
ALTER TABLE "ad_hoc_sales" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "announcements" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "announcements" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "applicant_stage_configs" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "applicant_stage_configs" ALTER COLUMN "educationLevelId" TYPE uuid USING NULLIF(trim("educationLevelId"), '')::uuid;
ALTER TABLE "applicant_stage_configs" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "applicant_stage_transitions" ALTER COLUMN "fromStageId" TYPE uuid USING NULLIF(trim("fromStageId"), '')::uuid;
ALTER TABLE "applicant_stage_transitions" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "applicant_stage_transitions" ALTER COLUMN "toStageId" TYPE uuid USING NULLIF(trim("toStageId"), '')::uuid;
ALTER TABLE "atp_series" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "atp_series" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "attendance_config" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "attendance_config" ALTER COLUMN "educationLevelId" TYPE uuid USING NULLIF(trim("educationLevelId"), '')::uuid;
ALTER TABLE "attendance_config" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "attendance_excuses" ALTER COLUMN "attendanceRecordId" TYPE uuid USING NULLIF(trim("attendanceRecordId"), '')::uuid;
ALTER TABLE "attendance_excuses" ALTER COLUMN "reviewedByUserId" TYPE uuid USING NULLIF(trim("reviewedByUserId"), '')::uuid;
ALTER TABLE "attendance_excuses" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "attendance_excuses" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "attendance_notification_thresholds" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "attendance_notification_thresholds" ALTER COLUMN "educationLevelId" TYPE uuid USING NULLIF(trim("educationLevelId"), '')::uuid;
ALTER TABLE "attendance_notification_thresholds" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "attendance_records" ALTER COLUMN "classOfferingId" TYPE uuid USING NULLIF(trim("classOfferingId"), '')::uuid;
ALTER TABLE "attendance_records" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "attendance_records" ALTER COLUMN "recordedByUserId" TYPE uuid USING NULLIF(trim("recordedByUserId"), '')::uuid;
ALTER TABLE "attendance_records" ALTER COLUMN "sectionId" TYPE uuid USING NULLIF(trim("sectionId"), '')::uuid;
ALTER TABLE "attendance_records" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "attendance_records" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "attendance_records" ALTER COLUMN "verifiedByUserId" TYPE uuid USING NULLIF(trim("verifiedByUserId"), '')::uuid;
ALTER TABLE "audit_events" ALTER COLUMN "actorUserId" TYPE uuid USING NULLIF(trim("actorUserId"), '')::uuid;
ALTER TABLE "audit_events" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "audit_events" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "behavior_incidents" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "behavior_incidents" ALTER COLUMN "reportedToUserId" TYPE uuid USING NULLIF(trim("reportedToUserId"), '')::uuid;
ALTER TABLE "behavior_incidents" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "behavior_incidents" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "buildings" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "buildings" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "calendar_events" ALTER COLUMN "calendarId" TYPE uuid USING NULLIF(trim("calendarId"), '')::uuid;
ALTER TABLE "calendar_events" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "cashier_sessions" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "cashier_sessions" ALTER COLUMN "cashierUserId" TYPE uuid USING NULLIF(trim("cashierUserId"), '')::uuid;
ALTER TABLE "cashier_sessions" ALTER COLUMN "stationId" TYPE uuid USING NULLIF(trim("stationId"), '')::uuid;
ALTER TABLE "cashier_sessions" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "cashier_stations" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "cashier_stations" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "channel_configs" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "channel_configs" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "facultyEmployeeId" TYPE uuid USING NULLIF(trim("facultyEmployeeId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "roomId" TYPE uuid USING NULLIF(trim("roomId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "sectionId" TYPE uuid USING NULLIF(trim("sectionId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "subjectId" TYPE uuid USING NULLIF(trim("subjectId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "class_offerings" ALTER COLUMN "termId" TYPE uuid USING NULLIF(trim("termId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "clonedFromCurriculumId" TYPE uuid USING NULLIF(trim("clonedFromCurriculumId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "educationLevelId" TYPE uuid USING NULLIF(trim("educationLevelId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "gradeLevelId" TYPE uuid USING NULLIF(trim("gradeLevelId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "programId" TYPE uuid USING NULLIF(trim("programId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "strandId" TYPE uuid USING NULLIF(trim("strandId"), '')::uuid;
ALTER TABLE "curricula" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "curriculum_subjects" ALTER COLUMN "coRequisiteSubjectId" TYPE uuid USING NULLIF(trim("coRequisiteSubjectId"), '')::uuid;
ALTER TABLE "curriculum_subjects" ALTER COLUMN "curriculumId" TYPE uuid USING NULLIF(trim("curriculumId"), '')::uuid;
ALTER TABLE "curriculum_subjects" ALTER COLUMN "effectiveGradingSystemId" TYPE uuid USING NULLIF(trim("effectiveGradingSystemId"), '')::uuid;
ALTER TABLE "curriculum_subjects" ALTER COLUMN "prerequisiteSubjectId" TYPE uuid USING NULLIF(trim("prerequisiteSubjectId"), '')::uuid;
ALTER TABLE "curriculum_subjects" ALTER COLUMN "subjectId" TYPE uuid USING NULLIF(trim("subjectId"), '')::uuid;
ALTER TABLE "curriculum_subjects" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "curriculum_subjects" ALTER COLUMN "termId" TYPE uuid USING NULLIF(trim("termId"), '')::uuid;
ALTER TABLE "custom_field_definitions" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "denomination_sets" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "departments" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "discount_types" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "document_requests" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "document_requests" ALTER COLUMN "documentTemplateId" TYPE uuid USING NULLIF(trim("documentTemplateId"), '')::uuid;
ALTER TABLE "document_requests" ALTER COLUMN "paymentId" TYPE uuid USING NULLIF(trim("paymentId"), '')::uuid;
ALTER TABLE "document_requests" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "document_requests" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "document_templates" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "dtr_records" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "dtr_records" ALTER COLUMN "employeeId" TYPE uuid USING NULLIF(trim("employeeId"), '')::uuid;
ALTER TABLE "dtr_records" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "education_levels" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "employees" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "employees" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "enrollment_holds" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "enrollment_holds" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "enrollment_holds" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "curriculumId" TYPE uuid USING NULLIF(trim("curriculumId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "gradeLevelId" TYPE uuid USING NULLIF(trim("gradeLevelId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "previousGradeLevelId" TYPE uuid USING NULLIF(trim("previousGradeLevelId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "previousSchoolYearId" TYPE uuid USING NULLIF(trim("previousSchoolYearId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "programId" TYPE uuid USING NULLIF(trim("programId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "sectionId" TYPE uuid USING NULLIF(trim("sectionId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "strandId" TYPE uuid USING NULLIF(trim("strandId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "enrollments" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "faculty_load_limits" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "faculty_load_limits" ALTER COLUMN "employeeId" TYPE uuid USING NULLIF(trim("employeeId"), '')::uuid;
ALTER TABLE "faculty_load_limits" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "feature_flags" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "feature_flags" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "fee_structure_items" ALTER COLUMN "feeStructureId" TYPE uuid USING NULLIF(trim("feeStructureId"), '')::uuid;
ALTER TABLE "fee_structure_items" ALTER COLUMN "feeTypeId" TYPE uuid USING NULLIF(trim("feeTypeId"), '')::uuid;
ALTER TABLE "fee_structure_items" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "educationLevelId" TYPE uuid USING NULLIF(trim("educationLevelId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "gradeLevelId" TYPE uuid USING NULLIF(trim("gradeLevelId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "programId" TYPE uuid USING NULLIF(trim("programId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "strandId" TYPE uuid USING NULLIF(trim("strandId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "fee_structures" ALTER COLUMN "termId" TYPE uuid USING NULLIF(trim("termId"), '')::uuid;
ALTER TABLE "fee_types" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "floors" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "generated_documents" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "generated_documents" ALTER COLUMN "requestId" TYPE uuid USING NULLIF(trim("requestId"), '')::uuid;
ALTER TABLE "generated_documents" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "generated_documents" ALTER COLUMN "templateId" TYPE uuid USING NULLIF(trim("templateId"), '')::uuid;
ALTER TABLE "generated_documents" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "approvedByUserId" TYPE uuid USING NULLIF(trim("approvedByUserId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "classOfferingId" TYPE uuid USING NULLIF(trim("classOfferingId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "gradeEntryId" TYPE uuid USING NULLIF(trim("gradeEntryId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "requestedByUserId" TYPE uuid USING NULLIF(trim("requestedByUserId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "grade_change_requests" ALTER COLUMN "workflowInstanceId" TYPE uuid USING NULLIF(trim("workflowInstanceId"), '')::uuid;
ALTER TABLE "grade_components" ALTER COLUMN "gradingSystemId" TYPE uuid USING NULLIF(trim("gradingSystemId"), '')::uuid;
ALTER TABLE "grade_components" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "classOfferingId" TYPE uuid USING NULLIF(trim("classOfferingId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "enteredByUserId" TYPE uuid USING NULLIF(trim("enteredByUserId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "gradeComponentId" TYPE uuid USING NULLIF(trim("gradeComponentId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "gradingSystemId" TYPE uuid USING NULLIF(trim("gradingSystemId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "grade_entries" ALTER COLUMN "termId" TYPE uuid USING NULLIF(trim("termId"), '')::uuid;
ALTER TABLE "grade_levels" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "grading_systems" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "grading_systems" ALTER COLUMN "educationLevelId" TYPE uuid USING NULLIF(trim("educationLevelId"), '')::uuid;
ALTER TABLE "grading_systems" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "grading_systems" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "guardians" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "health_records" ALTER COLUMN "recordedByUserId" TYPE uuid USING NULLIF(trim("recordedByUserId"), '')::uuid;
ALTER TABLE "health_records" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "health_records" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "honor_roll_configs" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "honor_roll_configs" ALTER COLUMN "educationLevelId" TYPE uuid USING NULLIF(trim("educationLevelId"), '')::uuid;
ALTER TABLE "honor_roll_configs" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "honor_roll_configs" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "installment_schedules" ALTER COLUMN "invoiceId" TYPE uuid USING NULLIF(trim("invoiceId"), '')::uuid;
ALTER TABLE "installment_schedules" ALTER COLUMN "paymentPlanId" TYPE uuid USING NULLIF(trim("paymentPlanId"), '')::uuid;
ALTER TABLE "installment_schedules" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "invoice_items" ALTER COLUMN "feeTypeId" TYPE uuid USING NULLIF(trim("feeTypeId"), '')::uuid;
ALTER TABLE "invoice_items" ALTER COLUMN "invoiceId" TYPE uuid USING NULLIF(trim("invoiceId"), '')::uuid;
ALTER TABLE "invoice_items" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "invoices" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "invoices" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "invoices" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "invoices" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "invoices" ALTER COLUMN "termId" TYPE uuid USING NULLIF(trim("termId"), '')::uuid;
ALTER TABLE "lookup_items" ALTER COLUMN "lookupListId" TYPE uuid USING NULLIF(trim("lookupListId"), '')::uuid;
ALTER TABLE "lookup_items" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "lookup_lists" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "message_threads" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "message_threads" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "message_threads" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "messages" ALTER COLUMN "senderUserId" TYPE uuid USING NULLIF(trim("senderUserId"), '')::uuid;
ALTER TABLE "messages" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "notification_logs" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "notification_logs" ALTER COLUMN "recipientUserId" TYPE uuid USING NULLIF(trim("recipientUserId"), '')::uuid;
ALTER TABLE "notification_logs" ALTER COLUMN "templateId" TYPE uuid USING NULLIF(trim("templateId"), '')::uuid;
ALTER TABLE "notification_logs" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "notification_rules" ALTER COLUMN "templateId" TYPE uuid USING NULLIF(trim("templateId"), '')::uuid;
ALTER TABLE "notification_rules" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "notification_templates" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "numbering_schemes" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "numbering_schemes" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "official_receipts" ALTER COLUMN "atpSeriesId" TYPE uuid USING NULLIF(trim("atpSeriesId"), '')::uuid;
ALTER TABLE "official_receipts" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "official_receipts" ALTER COLUMN "paymentId" TYPE uuid USING NULLIF(trim("paymentId"), '')::uuid;
ALTER TABLE "official_receipts" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "payment_allocations" ALTER COLUMN "invoiceId" TYPE uuid USING NULLIF(trim("invoiceId"), '')::uuid;
ALTER TABLE "payment_allocations" ALTER COLUMN "paymentId" TYPE uuid USING NULLIF(trim("paymentId"), '')::uuid;
ALTER TABLE "payment_allocations" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "payment_methods" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "payment_plans" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "payment_plans" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "payments" ALTER COLUMN "adHocSaleId" TYPE uuid USING NULLIF(trim("adHocSaleId"), '')::uuid;
ALTER TABLE "payments" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "payments" ALTER COLUMN "cashierSessionId" TYPE uuid USING NULLIF(trim("cashierSessionId"), '')::uuid;
ALTER TABLE "payments" ALTER COLUMN "invoiceId" TYPE uuid USING NULLIF(trim("invoiceId"), '')::uuid;
ALTER TABLE "payments" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "penalty_rules" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "penalty_rules" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "permanent_records" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "permanent_records" ALTER COLUMN "gradeLevelId" TYPE uuid USING NULLIF(trim("gradeLevelId"), '')::uuid;
ALTER TABLE "permanent_records" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "permanent_records" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "permanent_records" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "permanent_records" ALTER COLUMN "verifiedByUserId" TYPE uuid USING NULLIF(trim("verifiedByUserId"), '')::uuid;
ALTER TABLE "programs" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "promotion_decisions" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "promotion_decisions" ALTER COLUMN "gradeLevelId" TYPE uuid USING NULLIF(trim("gradeLevelId"), '')::uuid;
ALTER TABLE "promotion_decisions" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "promotion_decisions" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "promotion_decisions" ALTER COLUMN "targetGradeLevelId" TYPE uuid USING NULLIF(trim("targetGradeLevelId"), '')::uuid;
ALTER TABLE "promotion_decisions" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "rebac_edges" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "refunds" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "refunds" ALTER COLUMN "invoiceId" TYPE uuid USING NULLIF(trim("invoiceId"), '')::uuid;
ALTER TABLE "refunds" ALTER COLUMN "paymentId" TYPE uuid USING NULLIF(trim("paymentId"), '')::uuid;
ALTER TABLE "refunds" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "report_templates" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "role_permissions" ALTER COLUMN "permissionId" TYPE uuid USING NULLIF(trim("permissionId"), '')::uuid;
ALTER TABLE "role_permissions" ALTER COLUMN "roleId" TYPE uuid USING NULLIF(trim("roleId"), '')::uuid;
ALTER TABLE "roles" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "room_assets" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "room_assets" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "rooms" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "rooms" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "scheduled_reports" ALTER COLUMN "reportTemplateId" TYPE uuid USING NULLIF(trim("reportTemplateId"), '')::uuid;
ALTER TABLE "scheduled_reports" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "school_calendars" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "school_calendars" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "school_calendars" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "school_years" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "section_assignment_rules" ALTER COLUMN "sectionId" TYPE uuid USING NULLIF(trim("sectionId"), '')::uuid;
ALTER TABLE "section_assignment_rules" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "adviserEmployeeId" TYPE uuid USING NULLIF(trim("adviserEmployeeId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "gradeLevelId" TYPE uuid USING NULLIF(trim("gradeLevelId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "programId" TYPE uuid USING NULLIF(trim("programId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "roomId" TYPE uuid USING NULLIF(trim("roomId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "strandId" TYPE uuid USING NULLIF(trim("strandId"), '')::uuid;
ALTER TABLE "sections" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "series_counters" ALTER COLUMN "atpSeriesId" TYPE uuid USING NULLIF(trim("atpSeriesId"), '')::uuid;
ALTER TABLE "series_counters" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "series_counters" ALTER COLUMN "sessionId" TYPE uuid USING NULLIF(trim("sessionId"), '')::uuid;
ALTER TABLE "series_counters" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "strands" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_discount_grants" ALTER COLUMN "approvedByUserId" TYPE uuid USING NULLIF(trim("approvedByUserId"), '')::uuid;
ALTER TABLE "student_discount_grants" ALTER COLUMN "discountTypeId" TYPE uuid USING NULLIF(trim("discountTypeId"), '')::uuid;
ALTER TABLE "student_discount_grants" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "student_discount_grants" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "student_discount_grants" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_discount_grants" ALTER COLUMN "workflowInstanceId" TYPE uuid USING NULLIF(trim("workflowInstanceId"), '')::uuid;
ALTER TABLE "student_documents" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "student_documents" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_guardians" ALTER COLUMN "guardianId" TYPE uuid USING NULLIF(trim("guardianId"), '')::uuid;
ALTER TABLE "student_guardians" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "student_guardians" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_merge_audit" ALTER COLUMN "mergedStudentId" TYPE uuid USING NULLIF(trim("mergedStudentId"), '')::uuid;
ALTER TABLE "student_merge_audit" ALTER COLUMN "primaryStudentId" TYPE uuid USING NULLIF(trim("primaryStudentId"), '')::uuid;
ALTER TABLE "student_merge_audit" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_schedules" ALTER COLUMN "classOfferingId" TYPE uuid USING NULLIF(trim("classOfferingId"), '')::uuid;
ALTER TABLE "student_schedules" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "student_schedules" ALTER COLUMN "roomId" TYPE uuid USING NULLIF(trim("roomId"), '')::uuid;
ALTER TABLE "student_schedules" ALTER COLUMN "sectionId" TYPE uuid USING NULLIF(trim("sectionId"), '')::uuid;
ALTER TABLE "student_schedules" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "student_schedules" ALTER COLUMN "subjectId" TYPE uuid USING NULLIF(trim("subjectId"), '')::uuid;
ALTER TABLE "student_schedules" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_section_assignments" ALTER COLUMN "enrollmentId" TYPE uuid USING NULLIF(trim("enrollmentId"), '')::uuid;
ALTER TABLE "student_section_assignments" ALTER COLUMN "sectionId" TYPE uuid USING NULLIF(trim("sectionId"), '')::uuid;
ALTER TABLE "student_section_assignments" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "student_section_assignments" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "fromBranchId" TYPE uuid USING NULLIF(trim("fromBranchId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "fromGradeLevelId" TYPE uuid USING NULLIF(trim("fromGradeLevelId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "fromSchoolYearId" TYPE uuid USING NULLIF(trim("fromSchoolYearId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "studentId" TYPE uuid USING NULLIF(trim("studentId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "toBranchId" TYPE uuid USING NULLIF(trim("toBranchId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "toGradeLevelId" TYPE uuid USING NULLIF(trim("toGradeLevelId"), '')::uuid;
ALTER TABLE "student_transfers" ALTER COLUMN "toSchoolYearId" TYPE uuid USING NULLIF(trim("toSchoolYearId"), '')::uuid;
ALTER TABLE "students" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "students" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "subjects" ALTER COLUMN "coRequisiteSubjectId" TYPE uuid USING NULLIF(trim("coRequisiteSubjectId"), '')::uuid;
ALTER TABLE "subjects" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "teaching_loads" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "teaching_loads" ALTER COLUMN "classOfferingId" TYPE uuid USING NULLIF(trim("classOfferingId"), '')::uuid;
ALTER TABLE "teaching_loads" ALTER COLUMN "employeeId" TYPE uuid USING NULLIF(trim("employeeId"), '')::uuid;
ALTER TABLE "teaching_loads" ALTER COLUMN "schoolYearId" TYPE uuid USING NULLIF(trim("schoolYearId"), '')::uuid;
ALTER TABLE "teaching_loads" ALTER COLUMN "substituteForEmployeeId" TYPE uuid USING NULLIF(trim("substituteForEmployeeId"), '')::uuid;
ALTER TABLE "teaching_loads" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "teaching_loads" ALTER COLUMN "termId" TYPE uuid USING NULLIF(trim("termId"), '')::uuid;
ALTER TABLE "terms" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "tracks" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "user_person_links" ALTER COLUMN "personId" TYPE uuid USING NULLIF(trim("personId"), '')::uuid;
ALTER TABLE "user_person_links" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "user_person_links" ALTER COLUMN "userId" TYPE uuid USING NULLIF(trim("userId"), '')::uuid;
ALTER TABLE "user_roles" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "user_roles" ALTER COLUMN "roleId" TYPE uuid USING NULLIF(trim("roleId"), '')::uuid;
ALTER TABLE "user_roles" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "user_roles" ALTER COLUMN "userId" TYPE uuid USING NULLIF(trim("userId"), '')::uuid;
ALTER TABLE "user_sessions" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "user_sessions" ALTER COLUMN "userId" TYPE uuid USING NULLIF(trim("userId"), '')::uuid;
ALTER TABLE "users" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "withdrawal_policies" ALTER COLUMN "branchId" TYPE uuid USING NULLIF(trim("branchId"), '')::uuid;
ALTER TABLE "withdrawal_policies" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "workflow_approvals" ALTER COLUMN "approverUserId" TYPE uuid USING NULLIF(trim("approverUserId"), '')::uuid;
ALTER TABLE "workflow_approvals" ALTER COLUMN "instanceId" TYPE uuid USING NULLIF(trim("instanceId"), '')::uuid;
ALTER TABLE "workflow_approvals" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "workflow_definitions" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "workflow_instances" ALTER COLUMN "tenantId" TYPE uuid USING NULLIF(trim("tenantId"), '')::uuid;
ALTER TABLE "workflow_instances" ALTER COLUMN "workflowDefinitionId" TYPE uuid USING NULLIF(trim("workflowDefinitionId"), '')::uuid;
ALTER TABLE "user_roles" ALTER COLUMN "grantedBy" TYPE uuid USING NULLIF(trim("grantedBy"), '')::uuid;
\endif

-- ===== policy re-creates (101) =====
CREATE POLICY "tenant_isolation_users" ON "users" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_roles" ON "roles" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_user_roles" ON "user_roles" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_lookup_lists" ON "lookup_lists" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_custom_field_definitions" ON "custom_field_definitions" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_feature_flags" ON "feature_flags" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_enrollment_holds" ON "enrollment_holds" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_applicant_stage_configs" ON "applicant_stage_configs" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_attendance_excuses" ON "attendance_excuses" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_attendance_config" ON "attendance_config" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_channel_configs" ON "channel_configs" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_announcements" ON "announcements" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_atp_series" ON "atp_series" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_cashier_sessions" ON "cashier_sessions" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_ad_hoc_sale_items" ON "ad_hoc_sale_items" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_ad_hoc_sales" ON "ad_hoc_sales" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_tenants" ON "tenants" AS PERMISSIVE USING (((id)::text = current_setting('app.current_tenant_id'::text, true)));
CREATE POLICY "tenant_isolation_discount_types" ON "discount_types" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_education_levels" ON "education_levels" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_branches" ON "branches" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_buildings" ON "buildings" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_departments" ON "departments" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_fee_structure_items" ON "fee_structure_items" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_applicant_stage_transitions" ON "applicant_stage_transitions" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_attendance_notification_thresholds" ON "attendance_notification_thresholds" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_attendance_records" ON "attendance_records" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_audit_events" ON "audit_events" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_behavior_incidents" ON "behavior_incidents" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_calendar_events" ON "calendar_events" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_cashier_stations" ON "cashier_stations" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_class_offerings" ON "class_offerings" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_curricula" ON "curricula" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_curriculum_subjects" ON "curriculum_subjects" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_denomination_sets" ON "denomination_sets" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_document_requests" ON "document_requests" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_document_templates" ON "document_templates" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_dtr_records" ON "dtr_records" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_employees" ON "employees" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_enrollments" ON "enrollments" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_faculty_load_limits" ON "faculty_load_limits" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_fee_structures" ON "fee_structures" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_fee_types" ON "fee_types" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_floors" ON "floors" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_generated_documents" ON "generated_documents" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_grade_change_requests" ON "grade_change_requests" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_grade_components" ON "grade_components" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_grade_entries" ON "grade_entries" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_grade_levels" ON "grade_levels" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_grading_systems" ON "grading_systems" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_guardians" ON "guardians" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_health_records" ON "health_records" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_honor_roll_configs" ON "honor_roll_configs" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_installment_schedules" ON "installment_schedules" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_invoice_items" ON "invoice_items" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_invoices" ON "invoices" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_lookup_items" ON "lookup_items" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_message_threads" ON "message_threads" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_messages" ON "messages" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_notification_logs" ON "notification_logs" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_notification_rules" ON "notification_rules" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_notification_templates" ON "notification_templates" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_numbering_schemes" ON "numbering_schemes" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_official_receipts" ON "official_receipts" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_payment_allocations" ON "payment_allocations" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_payment_methods" ON "payment_methods" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_payment_plans" ON "payment_plans" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_payments" ON "payments" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_penalty_rules" ON "penalty_rules" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_permanent_records" ON "permanent_records" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_programs" ON "programs" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_rebac_edges" ON "rebac_edges" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_promotion_decisions" ON "promotion_decisions" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_refunds" ON "refunds" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_report_templates" ON "report_templates" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_room_assets" ON "room_assets" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_rooms" ON "rooms" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_scheduled_reports" ON "scheduled_reports" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_school_calendars" ON "school_calendars" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_school_years" ON "school_years" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_section_assignment_rules" ON "section_assignment_rules" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_sections" ON "sections" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_series_counters" ON "series_counters" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_strands" ON "strands" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_student_discount_grants" ON "student_discount_grants" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_student_documents" ON "student_documents" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_student_guardians" ON "student_guardians" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_student_merge_audit" ON "student_merge_audit" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_student_schedules" ON "student_schedules" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_student_section_assignments" ON "student_section_assignments" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_student_transfers" ON "student_transfers" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_students" ON "students" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_subjects" ON "subjects" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_teaching_loads" ON "teaching_loads" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_terms" ON "terms" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_tracks" ON "tracks" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_user_person_links" ON "user_person_links" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_user_sessions" ON "user_sessions" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_withdrawal_policies" ON "withdrawal_policies" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_workflow_approvals" ON "workflow_approvals" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_workflow_definitions" ON "workflow_definitions" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));
CREATE POLICY "tenant_isolation_workflow_instances" ON "workflow_instances" AS PERMISSIVE USING ((("tenantId")::text = current_setting('app.current_tenant_id'::text)));

COMMIT;
